import math
import decimal
import re

decimal.getcontext().prec = 10
graphPages = {}
d = 0.85

class Page:
    def __init__(self, page, rank, inLinkPages, noOfOutLinks):
        self.page = page
        self.rank = rank
        self.inLinkPages = inLinkPages
        self.noOfOutLinks = noOfOutLinks

    def setRank(self, value):
        self.rank = value

    def setnoOfOutLinks(self, value):
        self.noOfOutLinks = value

    def setinLinkPages(self, value):
        self.inLinkPages = value

def getSinkNodes():
    return {k: v for k, v in graphPages.items() if v.noOfOutLinks == 0}

def countInlink():
    return {k: v for k, v in graphPages.items() if len(v.inLinkPages) > 0}

def getSourceNodes():
    return {k: v for k, v in graphPages.items() if len(v.inLinkPages) == 0}

def countOutlink():
    return {k: v for k, v in graphPages.items() if v.noOfOutLinks > 0}

def getOutLinks(page):
    return {k: v for k, v in graphPages.items() if page in v.inLinkPages}

def perplexity(entropy):
    return (pow(2, decimal.Decimal(entropy)))

def entropy(rank):
    if rank <= 0:
        return 0
    entropy = rank * float(math.log(rank, 2))
    return entropy

def initializegraphPages(graphFile):
    print(f"Loading graph from {graphFile}...")
    with open(graphFile, 'r') as textFile:
        for line_num, line in enumerate(textFile.readlines(), 1):
            if line == '' or line == 's' or line == '\n':
                continue
            
            # Parse format: "source target1 target2 target3"
            parts = line.strip().split()
            if len(parts) < 2:
                continue
                
            source = parts[0]
            targets = parts[1:]
            
            # Add or update source node
            if source in graphPages:
                graphPages[source].setinLinkPages(targets)
            else:
                graphPages[source] = Page(source, 1.0, targets, 0)
            
            # Update outlink counts for targets
            for target in targets:
                if target in graphPages:
                    graphPages[target].noOfOutLinks += 1
                else:
                    graphPages[target] = Page(target, 1.0, [], 1)
            
            if line_num % 100 == 0:
                print(f"  Processed {line_num} lines...")
    
    print(f"Loaded {len(graphPages)} pages")

def calculatePageRank(sinkNodes):
    sinkPR = 0
    for node in sinkNodes:
        sinkPR += graphPages[node].rank

    pageIndex = 0
    totalEntropy = 0
    noOfPages = len(graphPages)

    for page in graphPages:
        newPR = (1 - d) / noOfPages
        newPR += d * sinkPR / noOfPages
        inLinks = graphPages[page].inLinkPages
        for link in inLinks:
            if link in graphPages:
                newPR += d * graphPages[link].rank / max(1, graphPages[link].noOfOutLinks)
        graphPages[page].setRank(newPR)
        totalEntropy += entropy(newPR)
    
    return perplexity(-totalEntropy)

# Main execution
print("Cranfield PageRank")
print("=" * 40)

# Use the linkgraph.txt generated by Graph.py
initializegraphPages("linkgraph.txt")

sinkNodes = getSinkNodes()
print(f"Sink Nodes: {len(sinkNodes)}")
for sn in list(sinkNodes)[:10]:  # Show first 10 sink nodes
    print(f"  {sn}")

sourceNodes = getSourceNodes()
inLinkCount = countInlink()
ouLinkCount = countOutlink()

print(f"Source Nodes: {len(sourceNodes)}")
print(f"Nodes with inlinks: {len(inLinkCount)}")
print(f"Nodes with outlinks: {len(ouLinkCount)}")

convergence = 0
round_num = 0
prevPerplexity = 0
curPerplexity = 0

print("\nRunning PageRank iterations...")
while convergence < 4 and round_num < 100:  # Max 100 iterations
    curPerplexity = calculatePageRank(sinkNodes)
    if abs((curPerplexity - prevPerplexity)) < 1:
        convergence += 1
    else:
        convergence = 0
    round_num += 1
    if round_num % 10 == 0:
        print(f"  Round {round_num}: Perplexity = {curPerplexity:.4f}")
    prevPerplexity = curPerplexity

print(f"\nConverged after {round_num} rounds")

# Write results
with open("cranfield_pagerank.txt", 'w') as textFile:
    pagesByRank = sorted(graphPages, key=lambda x: graphPages[x].rank, reverse=True)
    for idx, page in enumerate(pagesByRank[:500]):  # Top 500
        textFile.write('%s %.6f %d\n' % (page, graphPages[page].rank, len(graphPages[page].inLinkPages)))
        if idx < 20:  # Show top 20 in console
            print(f"  {idx+1}. {page}: {graphPages[page].rank:.6f} (inlinks: {len(graphPages[page].inLinkPages)})")

print("\nResults saved to cranfield_pagerank.txt")